import math

#
RES = WIDTH, HEIGHT = 1600, 900
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 0 # you can change the FPS

#
PLAYER_POSITION = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002

#
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH //2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ALGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

#
SCREE_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS